version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=dev
      - DB_PASSWORD=Password@1234
      - DB_NAME=bookmyshow
